# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d375b2733d7227e37916ca61b8d7487eaa3757b4fbae7337353025c1b6803d7a4f5566da5feee659eb880d436ef9f3963d61dc56ee07138a61799ded512b5a2

test:
  secret_key_base: 30a6e095f5969409b145a477edc1f6b1b0efa34691a1366886d6dd6e362b0f531f8badda95d936f21b8d63386c7674e1f89ddc295715983862f3cc6df7c25a08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
